# Generated by Django 4.2.16 on 2024-11-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("num", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="number", old_name="number", new_name="mobile",
        ),
    ]
