# Generated by Django 4.2.16 on 2024-11-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="部门名称")),
            ],
        ),
        migrations.CreateModel(
            name="User_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("pwd", models.CharField(max_length=32, verbose_name="密码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="账户余额"
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="入职时间")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.department"
                    ),
                ),
            ],
        ),
    ]
