# Generated by Django 4.2.16 on 2024-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_user_info_create_time_alter_user_info_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("pwd", models.CharField(max_length=32, verbose_name="密码")),
            ],
        ),
    ]
