# Generated by Django 4.2.16 on 2024-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_admin_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_info",
            name="pwd",
            field=models.CharField(max_length=100, verbose_name="密码"),
        ),
    ]
