# Generated by Django 4.2.16 on 2024-11-30 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_admin_info_pwd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="任务名称")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(0, "紧急"), (1, "重要"), (2, "普通")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                ("detail", models.TextField(verbose_name="任务详情")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.admin_info",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
