# Generated by Django 4.2.16 on 2024-11-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="城市名称")),
                ("count", models.IntegerField(verbose_name="人口数量")),
                ("img", models.FileField(upload_to="city", verbose_name="logo")),
            ],
        ),
    ]
